import { init } from 'license-checker';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SCAN_DIRS = [ROOT, path.join(ROOT, 'shared'), path.join(ROOT, 'agent-core')];

// First-party workspace packages are intentionally unlicensed (proprietary,
// AGENTS.md section a); they are not third-party dependencies under audit.
const FIRST_PARTY = new Set(['acute-code', '@acute/shared', '@acute/agent-core']);

const ALLOWED = new Set([
  'MIT',
  'Apache-2.0',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'ISC',
  'MPL-2.0',
  'CC0-1.0',
  'Unlicense',
  '0BSD',
]);

function scan(dir) {
  return new Promise((resolve) => {
    init({ start: dir, json: true }, (error, packages) => {
      resolve(error ? new Map() : new Map(Object.entries(packages ?? {})));
    });
  });
}

function normalizeLicenses(value) {
  if (Array.isArray(value)) return value.map((entry) => String(entry).trim());
  const single = String(value ?? 'UNKNOWN').trim().replace(/\*$/, '');
  return single ? [single] : [];
}

const merged = new Map();
for (const dir of SCAN_DIRS) {
  for (const [key, info] of await scan(dir)) {
    if (!merged.has(key)) merged.set(key, info);
  }
}

const packages = [];
const offenders = [];
const countsByLicense = new Map();

for (const [key, info] of merged) {
  const separator = key.lastIndexOf('@');
  if (FIRST_PARTY.has(key.slice(0, separator))) continue;
  const name = key.slice(0, separator);
  const version = key.slice(separator + 1);
  const licenses = normalizeLicenses(info.licenses);
  const label = licenses.length > 0 ? licenses.join(', ') : 'UNKNOWN';
  const ok = licenses.length > 0 && licenses.every((license) => ALLOWED.has(license));
  packages.push({ name, version, license: label, ok });
  for (const license of licenses) {
    countsByLicense.set(license, (countsByLicense.get(license) ?? 0) + 1);
  }
  if (!ok) offenders.push({ name, version, license: label });
}

packages.sort((a, b) => a.name.localeCompare(b.name));

const lines = [];
lines.push('# Dependency license compliance');
lines.push('');
lines.push('> Auto-generated by `pnpm audit:licenses` (`scripts/license-audit.mjs`). Do not edit by hand.');
lines.push('> Allowed licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, MPL-2.0, CC0-1.0, Unlicense, 0BSD.');
lines.push('');
lines.push(`Generated: ${new Date().toISOString()}`);
lines.push('');
lines.push(`- Packages audited: ${packages.length}`);
lines.push(`- Result: ${offenders.length === 0 ? 'PASS' : 'FAIL'}`);
lines.push('');

if (countsByLicense.size > 0) {
  lines.push('## Summary by license');
  lines.push('');
  lines.push('| License | Packages |');
  lines.push('| --- | --- |');
  for (const [license, count] of [...countsByLicense.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`| ${license} | ${count} |`);
  }
  lines.push('');
}

lines.push('## Packages');
lines.push('');
lines.push('| Package | Version | License |');
lines.push('| --- | --- | --- |');
for (const pkg of packages) {
  lines.push(`| ${pkg.name} | ${pkg.version} | ${pkg.license} |`);
}
lines.push('');

await mkdir(path.join(ROOT, 'docs', 'compliance'), { recursive: true });
await writeFile(path.join(ROOT, 'docs', 'compliance', 'dependency-licenses.md'), `${lines.join('\n')}\n`, 'utf8');

console.log(`License audit wrote docs/compliance/dependency-licenses.md (${packages.length} packages).`);

if (offenders.length > 0) {
  console.error(`License audit FAILED with ${offenders.length} offender(s):`);
  for (const offender of offenders) {
    console.error(`  ${offender.name}@${offender.version} -> ${offender.license}`);
  }
  process.exitCode = 1;
} else {
  console.log('License audit PASSED.');
}